final List<Map<String, String>> dataDivisi = [
  {
    'nama': 'Leader of ITC',
    'foto': 'assets/images/ketua.png',
    'foto_detail': 'assets/images/ketua.png',
    'nama_lengkap': 'Pemimpin Information Technology Club',
    'deskripsi':
        'Ketua dan Wakil bertanggung jawab penuh dalam memimpin dan mengarahkan ITC. Tugas utamanya meliputi pengambilan keputusan strategis, mengoordinasi seluruh divisi, serta menjadi wajah organisasi dalam menjalin kerja sama dengan pihak eksternal. Ketua memastikan visi dan misi organisasi tercapai dengan harmonis.',
    'num_members': '2',
    'member_foto_1': 'assets/images/leader.png',
    'member_nama_1': 'Grace Rianty Butar Butar',
    'member_jabatan_1': 'Ketua',
    'member_ig_1': '@graceriantyy',
    'member_wa_1': '081265634644',
    'member_foto_2': 'assets/images/wakil.png',
    'member_nama_2': 'Dzaki Ghatfaan Abhipraya',
    'member_jabatan_2': 'Wakil Ketua',
    'member_ig_2': '@xaki_to',
    'member_wa_2': '08975882422',
  },
  {
    'nama': 'Secretary & Treasury',
    'foto': 'assets/images/secretary.png',
    'foto_detail': 'assets/images/secretary.png',
    'nama_lengkap': 'Sekretaris & Bendahara',
    'deskripsi':
        'Sekretaris bertanggung jawab penuh atas pengelolaan persuratan, pengarsipan dokumen penting, hingga pencatatan notulensi rapat. Sementara itu, Bendahara bertugas mengelola arus kas, menyusun rancangan anggaran kegiatan, serta memastikan transparansi keuangan ITC agar seluruh program kerja dapat berjalan dengan lancar dan terstruktur.',
    'num_members': '2',
    'member_foto_1': 'assets/images/sekre.png',
    'member_nama_1': 'Nayla Saskia Zallianti',
    'member_jabatan_1': 'Sekretaris',
    'member_ig_1': '@naylasaskiaaa',
    'member_foto_2': 'assets/images/bend.png',
    'member_nama_2': 'Dewi Rahmawati',
    'member_jabatan_2': 'Bendahara',
    'member_ig_2': '@dewsynn',
  },
  {
    'nama': 'Medinfo',
    'foto': 'assets/images/medinfo.png',
    'foto_detail': 'assets/images/medinfo.png',
    'nama_lengkap': 'Media & Informasi',
    'deskripsi':
        'Divisi ini bertanggung jawab atas pengelolaan seluruh platform media sosial organisasi, pembuatan konten visual yang menarik (desain grafis dan video), serta dokumentasi di setiap kegiatan.',
    'num_members': '3',
    'member_foto_1': 'assets/images/med1.png',
    'member_nama_1': 'M. Rafli Wibowo',
    'member_jabatan_1': 'Medinfo',
    'member_ig_1': '@muhmdraflyyy',
    'member_foto_2': 'assets/images/med2.png',
    'member_nama_2': 'Satya Dio Putranto',
    'member_jabatan_2': 'Medinfo',
    'member_ig_2': '@diooo_o_',
    'member_foto_3': 'assets/images/med3.png',
    'member_nama_3': 'Wilda Nafian',
    'member_jabatan_3': 'Medinfo',
    'member_ig_3': '@navianwldn',
  },
  {
    'nama': 'Web Development',
    'foto': 'assets/images/webdev.png',
    'foto_detail': 'assets/images/webdev.png',
    'nama_lengkap': 'Website Development',
    'deskripsi':
        'Divisi Web Development berfokus pada perancangan, pembuatan, dan pemeliharaan situs web. Divisi ini menjadi tempat bagi anggota untuk mempelajari berbagai teknologi web, mulai dari merancang antarmuka pengguna (Front-end) hingga pengelolaan database dan server di balik layar (Back-end).',
    'num_members': '3',
    'member_foto_1': 'assets/images/kweb.png',
    'member_nama_1': 'Gradiva Arya Wicaksana',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': '@grdv_arya',
    'member_wa_1': '081325980158',
    'member_foto_2': 'assets/images/wweb1.png',
    'member_nama_2': 'Farhannivta Ramadhana',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@frhnvtaaa',
    'member_wa_2': '088225357849',
    'member_foto_3': 'assets/images/wweb2.png',
    'member_nama_3': 'Marvel Valensiano',
    'member_jabatan_3': 'Wakil Kepala Divisi',
    'member_ig_3': '@marvel_valensiano._',
    'member_wa_3': '087860211380',
  },
  {
    'nama': 'Mobile Development',
    'foto': 'assets/images/mobdev.png',
    'foto_detail': 'assets/images/mobdev.png',
    'nama_lengkap': 'Mobile Development',
    'deskripsi':
        'Divisi Mobile Development berfokus pada perancangan dan pembuatan aplikasi untuk perangkat smartphone, baik Android maupun iOS. Selain mempelajari berbagai bahasa pemrograman dan framework terkini (seperti Flutter), divisi ini juga aktif berinovasi menciptakan solusi digital yang praktis, interaktif, dan user-friendly.',
    'num_members': '2',
    'member_foto_1': 'assets/images/kmob.png',
    'member_nama_1': 'Bintoro',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': '@_linkebin',
    'member_wa_1': '087831544359',
    'member_foto_2': 'assets/images/wmob.png',
    'member_nama_2': 'Ikhsan Fillah Hidayat',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@ikhsannflh',
    'member_wa_2': '087718531758',
  },
  {
    'nama': 'Competitive Programming',
    'foto': 'assets/images/cp.png',
    'foto_detail': 'assets/images/cp.png',
    'nama_lengkap': 'Competitive Programming',
    'deskripsi':
        'Divisi Competitive Programming (CP) Berbeda dengan divisi lain yang fokus pada pembuatan produk (aplikasi/web), divisi ini berfokus pada penguasaan struktur data, algoritma, dan penulisan kode yang efisien serta secepat mungkin. Divisi ini melatih kemampuan berpikir kritis dan menjadi wadah persiapan bagi para perwakilan ITC untuk bertanding di berbagai ajang kompetisi coding tingkat nasional.',
    'num_members': '2',
    'member_foto_1': 'assets/images/kcp.png',
    'member_nama_1': 'Mochamad Rizal Ardiansyah Sucipno',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': ' @rizalards_',
    'member_wa_1': '085159935366',
    'member_foto_2': 'assets/images/wcp.png',
    'member_nama_2': 'Filipus Satrio Dewaki Tyasing Suryo',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@satrio._.dewaki',
    'member_wa_2': '085157227142',
  },
  {
    'nama': 'UI/UX Design',
    'foto': 'assets/images/uiux.png',
    'foto_detail': 'assets/images/uiux.png',
    'nama_lengkap': 'User Interface (UI) & User Experience (UX) Design',
    'deskripsi':
        'Divisi UI/UX adalah divisi yang berfokus pada perancangan tampilan visual produk digital (UI) agar terlihat estetis dan modern, sekaligus memastikan pengalaman pengguna (UX) saat menggunakannya terasa mudah, nyaman, dan intuitif.',
    'num_members': '2',
    'member_foto_1': 'assets/images/kui.png',
    'member_nama_1': 'Muhammad Ruhul Jadid',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': '@mruhulj',
    'member_wa_1': '089656600124',
    'member_foto_2': 'assets/images/wui.png',
    'member_nama_2': 'Gita Ristya',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@gitarrsy',
    'member_wa_2': '081221532929',
  },
  {
    'nama': 'AI & Machine Learning',
    'foto': 'assets/images/ai.png',
    'foto_detail': 'assets/images/ai.png',
    'nama_lengkap': 'Artificial intelligence & Machine Learning',
    'deskripsi':
        'Divisi AI & Machine Learning berfokus pada eksplorasi teknologi masa depan yang memungkinkan komputer untuk belajar dari data dan mengambil keputusan secara mandiri.',
    'num_members': '2',
    'member_foto_1': 'assets/images/kai.png',
    'member_nama_1': 'Bintang Ramadhan',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': '@tangrmdhn',
    'member_wa_1': '089638790525',
    'member_foto_2': 'assets/images/wai.png',
    'member_nama_2': 'Muhammad Dimas Setiaji',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@mdimassetiaji',
    'member_wa_2': '085725169979',
  },
  {
    'nama': 'Project Manager',
    'foto': 'assets/images/pm.png',
    'foto_detail': 'assets/images/pm.png',
    'nama_lengkap': 'Project Manager',
    'deskripsi':
        'Divisi Project Management (PM) adalah jembatan penghubung antara ide dan eksekusi. Divisi ini bertanggung jawab untuk merencanakan, mengatur, dan mengawasi jalannya sebuah proyek aplikasi atau web dari awal hingga rilis.',
    'num_members': '2',
    'member_foto_1': 'assets/images/kpm.png',
    'member_nama_1': 'Kurniasari Salasa',
    'member_jabatan_1': 'Kepala Divisi',
    'member_ig_1': '@kurniasarisall_',
    'member_wa_1': '085640648901',
    'member_foto_2': 'assets/images/wpm.png',
    'member_nama_2': 'Fahri Hidayatullah',
    'member_jabatan_2': 'Wakil Kepala Divisi',
    'member_ig_2': '@fhri_hdytllah07',
    'member_wa_2': '085664320806',
  },
];

const List<Map<String, String>> ringkasanDivisi = [
  {
    'judul': 'Web Development',
    'deskripsi':
        'Mempelajari dan mengembangkan website modern dengan teknologi terbaru dari sisi Front-End hingga Back-End.',
  },
  {
    'judul': 'Mobile Development',
    'deskripsi':
        'Fokus pada pembuatan aplikasi mobile (Android & iOS) yang responsif dan user-friendly.',
  },
  {
    'judul': 'UI/UX Design',
    'deskripsi':
        'Merancang antarmuka aplikasi yang menarik secara visual dan menciptakan pengalaman pengguna yang optimal.',
  },
  {
    'judul': 'Project Manager',
    'deskripsi':
        'Mengelola jalannya proyek, memfasilitasi komunikasi tim, dan memastikan setiap target pengembangan aplikasi tercapai dengan efisien.',
  },
  {
    'judul': 'AI & Machine Learning',
    'deskripsi':
        'Mempelajari kecerdasan buatan, pemrosesan data, dan melatih algoritma agar sistem dapat belajar serta mengambil keputusan secara otomatis.',
  },
  {
    'judul': 'Competitive Programming',
    'deskripsi':
        'Melatih logika tingkat lanjut, struktur data, dan pemecahan masalah (problem solving) algoritma secara cepat untuk persiapan kompetisi coding.',
  },
];
